var MENU = {
    "destaque": [
        {
            "id": "conjunto-laura-farm",
            "img": "./img/products/destaque/f1.jpg",
            "imgdetalheum": "./img/products/destaque/f2.jpg",
            "imgdetalhedois": "./img/products/destaque/f3.jpg",
            "imgdetalhetres": "./img/products/destaque/f4.jpg",
            "name": "Conjunto Laura Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 84.90
        },
        {
            "id": "conjunto-mali-farm",
            "img": "./img/products/destaque/f2.jpg",
            "imgdetalheum": "./img/products/destaque/f2.jpg",
            "imgdetalhedois": "./img/products/destaque/f3.jpg",
            "imgdetalhetres": "./img/products/destaque/f4.jpg",
            "name": "Conjunto Mali Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 84.90
        },
        {
            "id": "conjunto-liz-vermelho",
            "img": "./img/products/destaque/f4.jpg",
            "imgdetalheum": "./img/products/destaque/f2.jpg",
            "imgdetalhedois": "./img/products/destaque/f3.jpg",
            "imgdetalhetres": "./img/products/destaque/f4.jpg",
            "name": "Conjunto Liz",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
        {
            "id": "macaquinho-tania-farm",
            "img": "./img/products/destaque/f3.jpg",
            "imgdetalheum": "./img/products/destaque/f2.jpg",
            "imgdetalhedois": "./img/products/destaque/f3.jpg",
            "imgdetalhetres": "./img/products/destaque/f4.jpg",
            "name": "Macaquinho Tânia Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
        
    ],
    "recemchegadas": [
        {
            "id": "conjunto-farm-saia",
            "img": "./img/products/recem-chegadas/1.png",
            "imgdetalheum": "./img/products/recem-chegadas/1.png",
            "imgdetalhedois": "./img/products/recem-chegadas/1.png",
            "imgdetalhetres": "./img/products/recem-chegadas/1.png",
            "name": "Conjunto Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
        {
            "id": "conjunto-farm-short",
            "img": "./img/products/recem-chegadas/2.png",
            "imgdetalheum": "./img/products/recem-chegadas/2.png",
            "imgdetalhedois": "./img/products/recem-chegadas/2.png",
            "imgdetalhetres": "./img/products/recem-chegadas/2.png",
            "name": "Conjunto Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
        {
            "id": "conjunto-farm-short-blue",
            "img": "./img/products/recem-chegadas/3.png",
            "imgdetalheum": "./img/products/recem-chegadas/3.png",
            "imgdetalhedois": "./img/products/recem-chegadas/3.png",
            "imgdetalhetres": "./img/products/recem-chegadas/3.png",
            "name": "Conjunto Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
        {
            "id": "macaquinho-farm",
            "img": "./img/products/recem-chegadas/4.png",
            "imgdetalheum": "./img/products/recem-chegadas/4.png",
            "imgdetalhedois": "./img/products/recem-chegadas/4.png",
            "imgdetalhetres": "./img/products/recem-chegadas/4.png",
            "name": "Macaquinho Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
    ],
    "conjunto": [
        {
            "id": "conjunto-laura-farm",
            "img": "./img/products/destaque/f1.jpg",
            "imgdetalheum": "./img/products/destaque/f2.jpg",
            "imgdetalhedois": "./img/products/destaque/f3.jpg",
            "imgdetalhetres": "./img/products/destaque/f4.jpg",
            "name": "Conjunto Laura Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 84.90
        },
        {
            "id": "conjunto-mali-farm",
            "img": "./img/products/destaque/f2.jpg",
            "imgdetalheum": "./img/products/destaque/f2.jpg",
            "imgdetalhedois": "./img/products/destaque/f3.jpg",
            "imgdetalhetres": "./img/products/destaque/f4.jpg",
            "name": "Conjunto Mali Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 84.90
        },
        {
            "id": "conjunto-liz",
            "img": "./img/products/conjuntos/10.png",
            "imgdetalheum": "./img/products/recem-chegadas/4.png",
            "imgdetalhedois": "./img/products/recem-chegadas/4.png",
            "imgdetalhetres": "./img/products/recem-chegadas/4.png",
            "name": "Conjunto Liz",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.99
        },
        {
            "id": "conjunto-farm-saia",
            "img": "./img/products/conjuntos/1.png",
            "imgdetalheum": "./img/products/recem-chegadas/1.png",
            "imgdetalhedois": "./img/products/recem-chegadas/1.png",
            "imgdetalhetres": "./img/products/recem-chegadas/1.png",
            "name": "Conjunto Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
        {
            "id": "conjunto-farm-short",
            "img": "./img/products/conjuntos/4.png",
            "imgdetalheum": "./img/products/recem-chegadas/2.png",
            "imgdetalhedois": "./img/products/recem-chegadas/2.png",
            "imgdetalhetres": "./img/products/recem-chegadas/2.png",
            "name": "Conjunto Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
        {
            "id": "conjunto-farm-short-blue",
            "img": "./img/products/conjuntos/5.png",
            "imgdetalheum": "./img/products/recem-chegadas/3.png",
            "imgdetalhedois": "./img/products/recem-chegadas/3.png",
            "imgdetalhetres": "./img/products/recem-chegadas/3.png",
            "name": "Conjunto Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
    ],
    "macaquinho": [
        {
            "id": "macaquinho-tania-farm",
            "img": "./img/products/macaquinho/6.png",
            "imgdetalheum": "./img/products/destaque/f2.jpg",
            "imgdetalhedois": "./img/products/destaque/f3.jpg",
            "imgdetalhetres": "./img/products/destaque/f4.jpg",
            "name": "Macaquinho Tânia Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
        {
            "id": "macaquinho-farm",
            "img": "./img/products/macaquinho/4.png",
            "imgdetalheum": "./img/products/recem-chegadas/4.png",
            "imgdetalhedois": "./img/products/recem-chegadas/4.png",
            "imgdetalhetres": "./img/products/recem-chegadas/4.png",
            "name": "Macaquinho Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
        {
            "id": "macaquinho-helena-farm",
            "img": "./img/products/macaquinho/7.png",
            "imgdetalheum": "./img/products/recem-chegadas/4.png",
            "imgdetalhedois": "./img/products/recem-chegadas/4.png",
            "imgdetalhetres": "./img/products/recem-chegadas/4.png",
            "name": "Macaquinho Helena Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 74.90
        },
        
    ],
    "short": [
        {
            "id": "short-zara",
            "img": "./img/products/short/Short Zara Nude.png",
            "imgdetalheum": "./img/products/recem-chegadas/4.png",
            "imgdetalhedois": "./img/products/recem-chegadas/4.png",
            "imgdetalhetres": "./img/products/recem-chegadas/4.png",
            "name": "Short Zara",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 55.90
        },
        {
            "id": "short-saia",
            "img": "./img/products/short/5.png",
            "imgdetalheum": "./img/products/recem-chegadas/4.png",
            "imgdetalhedois": "./img/products/recem-chegadas/4.png",
            "imgdetalhetres": "./img/products/recem-chegadas/4.png",
            "name": "Short Saia",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 55.90
        },
    ],
    "cropped": [
        {
            "id": "cropped-cortininha-azul-marinho",
            "img": "./img/products/cropped/1.png",
            "imgdetalheum": "./img/products/recem-chegadas/4.png",
            "imgdetalhedois": "./img/products/recem-chegadas/4.png",
            "imgdetalhetres": "./img/products/recem-chegadas/4.png",
            "name": "Cropped Cortininha",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 55.90
        },
        {
            "id": "cropped-farm-um",
            "img": "./img/products/cropped/4.png",
            "imgdetalheum": "./img/products/recem-chegadas/4.png",
            "imgdetalhedois": "./img/products/recem-chegadas/4.png",
            "imgdetalhetres": "./img/products/recem-chegadas/4.png",
            "name": "Cropped Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 49.90
        },
        {
            "id": "cropped-farm-dois",
            "img": "./img/products/cropped/8.png",
            "imgdetalheum": "./img/products/recem-chegadas/4.png",
            "imgdetalhedois": "./img/products/recem-chegadas/4.png",
            "imgdetalhetres": "./img/products/recem-chegadas/4.png",
            "name": "Cropped Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 49.90
        },
        {
            "id": "cropped-farm-tres",
            "img": "./img/products/cropped/9.png",
            "imgdetalheum": "./img/products/recem-chegadas/4.png",
            "imgdetalhedois": "./img/products/recem-chegadas/4.png",
            "imgdetalhetres": "./img/products/recem-chegadas/4.png",
            "name": "Cropped Farm",
            "corum": "Azul",
            "cordois": "Amarelo",
            "cortres": "Rosa",
            "dsc": "Veste do tamanho P ao M",
            "price": 49.90
        },
        
    ],
    
}